name: stammtisch_app
description: Eine App zur Organisation eines privaten Stammtischs.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.1.2
  uuid: ^4.5.1
  shared_preferences: ^2.3.4
  table_calendar: ^3.1.2
  http: ^1.4.0
  geolocator: ^14.0.2
  flutter_dotenv: ^5.2.1
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
  generate: true