name: stammtisch_app
description: Eine App zur Organisation eines privaten Stammtischs.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.1.0
  uuid: ^4.3.1  # ➕ Hinzugefügt für Gruppenerstellung
  shared_preferences: ^2.2.2
  table_calendar: ^3.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
