name: stammtisch_app
description: Eine App zur Organisation eines privaten Stammtischs.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.1.0
  uuid: ^4.3.1
  shared_preferences: ^2.2.2
  table_calendar: ^3.0.8
  # Google Places API Integration
  http: ^1.1.0
  geolocator: ^10.1.0
  # Environment Variables
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - .env