// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCz8F6-4vRCQX_Qx_Qx_Qx_Qx_Qx_Qx',
    appId: '1:545936481270:web:5d297b640d67f06e3c45d7',
    messagingSenderId: '545936481270',
    projectId: 'stammtischapp-47cfc',
    authDomain: 'stammtischapp-47cfc.firebaseapp.com',
    storageBucket: 'stammtischapp-47cfc.appspot.com',
    measurementId: 'G-XXXXXXXXXX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCz8F6-4vRCQX_Qx_Qx_Qx_Qx_Qx_Qx',
    appId: '1:545936481270:android:d2410777b55936903c45d7',
    messagingSenderId: '545936481270',
    projectId: 'stammtischapp-47cfc',
    storageBucket: 'stammtischapp-47cfc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCz8F6-4vRCQX_Qx_Qx_Qx_Qx_Qx_Qx',
    appId: '1:545936481270:ios:cf80a487e4616eb83c45d7',
    messagingSenderId: '545936481270',
    projectId: 'stammtischapp-47cfc',
    storageBucket: 'stammtischapp-47cfc.appspot.com',
    iosBundleId: 'com.example.stammtischApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCz8F6-4vRCQX_Qx_Qx_Qx_Qx_Qx_Qx',
    appId: '1:545936481270:ios:cf80a487e4616eb83c45d7',
    messagingSenderId: '545936481270',
    projectId: 'stammtischapp-47cfc',
    storageBucket: 'stammtischapp-47cfc.appspot.com',
    iosBundleId: 'com.example.stammtischApp',
  );
}